const paises = [
    { codigo: 'AF', nombre: 'Afganistán' },
    { codigo: 'AL', nombre: 'Albania' },
    { codigo: 'DZ', nombre: 'Argelia' },
    { codigo: 'AD', nombre: 'Andorra' },
    { codigo: 'AO', nombre: 'Angola' },
    { codigo: 'AG', nombre: 'Antigua y Barbuda' },
    { codigo: 'AR', nombre: 'Argentina' },
    { codigo: 'AM', nombre: 'Armenia' },
    { codigo: 'AU', nombre: 'Australia' },
    { codigo: 'AT', nombre: 'Austria' },
    { codigo: 'AZ', nombre: 'Azerbaiyán' },
    { codigo: 'BS', nombre: 'Bahamas' },
    { codigo: 'BH', nombre: 'Baréin' },
    { codigo: 'BD', nombre: 'Bangladés' },
    { codigo: 'BB', nombre: 'Barbados' },
    { codigo: 'BY', nombre: 'Bielorrusia' },
    { codigo: 'BE', nombre: 'Bélgica' },
    { codigo: 'BZ', nombre: 'Belice' },
    { codigo: 'BJ', nombre: 'Benín' },
    { codigo: 'BT', nombre: 'Bután' },
    { codigo: 'BO', nombre: 'Bolivia' },
    { codigo: 'BA', nombre: 'Bosnia y Herzegovina' },
    { codigo: 'BW', nombre: 'Botsuana' },
    { codigo: 'BR', nombre: 'Brasil' },
    { codigo: 'BN', nombre: 'Brunéi' },
    { codigo: 'BG', nombre: 'Bulgaria' },
    { codigo: 'BF', nombre: 'Burkina Faso' },
    { codigo: 'BI', nombre: 'Burundi' },
    { codigo: 'CV', nombre: 'Cabo Verde' },
    { codigo: 'KH', nombre: 'Camboya' },
    { codigo: 'CM', nombre: 'Camerún' },
    { codigo: 'CA', nombre: 'Canadá' },
    { codigo: 'CF', nombre: 'República Centroafricana' },
    { codigo: 'TD', nombre: 'Chad' },
    { codigo: 'CL', nombre: 'Chile' },
    { codigo: 'CN', nombre: 'China' },
    { codigo: 'CO', nombre: 'Colombia' },
    { codigo: 'KM', nombre: 'Comoras' },
    { codigo: 'CG', nombre: 'Congo' },
    { codigo: 'CD', nombre: 'República Democrática del Congo' },
    { codigo: 'CR', nombre: 'Costa Rica' },
    { codigo: 'CI', nombre: 'Costa de Marfil' },
    { codigo: 'HR', nombre: 'Croacia' },
    { codigo: 'CU', nombre: 'Cuba' },
    { codigo: 'CY', nombre: 'Chipre' },
    { codigo: 'CZ', nombre: 'República Checa' },
    { codigo: 'DK', nombre: 'Dinamarca' },
    { codigo: 'DJ', nombre: 'Yibuti' },
    { codigo: 'DM', nombre: 'Dominica' },
    { codigo: 'DO', nombre: 'República Dominicana' },
    { codigo: 'EC', nombre: 'Ecuador' },
    { codigo: 'EG', nombre: 'Egipto' },
    { codigo: 'SV', nombre: 'El Salvador' },
    { codigo: 'GQ', nombre: 'Guinea Ecuatorial' },
    { codigo: 'ER', nombre: 'Eritrea' },
    { codigo: 'EE', nombre: 'Estonia' },
    { codigo: 'ET', nombre: 'Etiopía' },
    { codigo: 'FJ', nombre: 'Fiyi' },
    { codigo: 'FI', nombre: 'Finlandia' },
    { codigo: 'FR', nombre: 'Francia' },
    { codigo: 'GA', nombre: 'Gabón' },
    { codigo: 'GM', nombre: 'Gambia' },
    { codigo: 'GE', nombre: 'Georgia' },
    { codigo: 'DE', nombre: 'Alemania' },
    { codigo: 'GH', nombre: 'Ghana' },
    { codigo: 'GR', nombre: 'Grecia' },
    { codigo: 'GD', nombre: 'Granada' },
    { codigo: 'GT', nombre: 'Guatemala' },
    { codigo: 'GN', nombre: 'Guinea' },
    { codigo: 'GW', nombre: 'Guinea-Bisáu' },
    { codigo: 'GY', nombre: 'Guyana' },
    { codigo: 'HT', nombre: 'Haití' },
    { codigo: 'HN', nombre: 'Honduras' },
    { codigo: 'HU', nombre: 'Hungría' },
    { codigo: 'IS', nombre: 'Islandia' },
    { codigo: 'IN', nombre: 'India' },
    { codigo: 'ID', nombre: 'Indonesia' },
    { codigo: 'IR', nombre: 'Irán' },
    { codigo: 'IQ', nombre: 'Irak' },
    { codigo: 'IE', nombre: 'Irlanda' },
    { codigo: 'IL', nombre: 'Israel' },
    { codigo: 'IT', nombre: 'Italia' },
    { codigo: 'JM', nombre: 'Jamaica' },
    { codigo: 'JP', nombre: 'Japón' },
    { codigo: 'JO', nombre: 'Jordania' },
    { codigo: 'KZ', nombre: 'Kazajistán' },
    { codigo: 'KE', nombre: 'Kenia' },
    { codigo: 'KI', nombre: 'Kiribati' },
    { codigo: 'KW', nombre: 'Kuwait' },
    { codigo: 'KG', nombre: 'Kirguistán' },
    { codigo: 'LA', nombre: 'Laos' },
    { codigo: 'LV', nombre: 'Letonia' },
    { codigo: 'LB', nombre: 'Líbano' },
    { codigo: 'LS', nombre: 'Lesoto' },
    { codigo: 'LR', nombre: 'Liberia' },
    { codigo: 'LY', nombre: 'Libia' },
    { codigo: 'LI', nombre: 'Liechtenstein' },
    { codigo: 'LT', nombre: 'Lituania' },
    { codigo: 'LU', nombre: 'Luxemburgo' },
    { codigo: 'MK', nombre: 'Macedonia del Norte' },
    { codigo: 'MG', nombre: 'Madagascar' },
    { codigo: 'MW', nombre: 'Malaui' },
    { codigo: 'MY', nombre: 'Malasia' },
    { codigo: 'MV', nombre: 'Maldivas' },
    { codigo: 'ML', nombre: 'Mali' },
    { codigo: 'MT', nombre: 'Malta' },
    { codigo: 'MH', nombre: 'Islas Marshall' },
    { codigo: 'MR', nombre: 'Mauritania' },
    { codigo: 'MU', nombre: 'Mauricio' },
    { codigo: 'MX', nombre: 'México' },
    { codigo: 'FM', nombre: 'Micronesia' },
    { codigo: 'MD', nombre: 'Moldavia' },
    { codigo: 'MC', nombre: 'Mónaco' },
    { codigo: 'MN', nombre: 'Mongolia' },
    { codigo: 'ME', nombre: 'Montenegro' },
    { codigo: 'MA', nombre: 'Marruecos' },
    { codigo: 'MZ', nombre: 'Mozambique' },
    { codigo: 'MM', nombre: 'Myanmar' },
    { codigo: 'NA', nombre: 'Namibia' },
    { codigo: 'NR', nombre: 'Nauru' },
    { codigo: 'NP', nombre: 'Nepal' },
    { codigo: 'NL', nombre: 'Países Bajos' },
    { codigo: 'NZ', nombre: 'Nueva Zelanda' },
    { codigo: 'NI', nombre: 'Nicaragua' },
    { codigo: 'NE', nombre: 'Níger' },
    { codigo: 'NG', nombre: 'Nigeria' },
    { codigo: 'KP', nombre: 'Corea del Norte' },
    { codigo: 'NO', nombre: 'Noruega' },
    { codigo: 'OM', nombre: 'Omán' },
    { codigo: 'PK', nombre: 'Pakistán' },
    { codigo: 'PW', nombre: 'Palau' },
    { codigo: 'PA', nombre: 'Panamá' },
    { codigo: 'PG', nombre: 'Papúa Nueva Guinea' },
    { codigo: 'PY', nombre: 'Paraguay' },
    { codigo: 'PE', nombre: 'Perú' },
    { codigo: 'PH', nombre: 'Filipinas' },
    { codigo: 'PL', nombre: 'Polonia' },
    { codigo: 'PT', nombre: 'Portugal' },
    { codigo: 'QA', nombre: 'Catar' },
    { codigo: 'RO', nombre: 'Rumania' },
    { codigo: 'RU', nombre: 'Rusia' },
    { codigo: 'RW', nombre: 'Ruanda' },
    { codigo: 'KN', nombre: 'San Cristóbal y Nieves' },
    { codigo: 'LC', nombre: 'Santa Lucía' },
    { codigo: 'VC', nombre: 'San Vicente y las Granadinas' },
    { codigo: 'WS', nombre: 'Samoa' },
    { codigo: 'SM', nombre: 'San Marino' },
    { codigo: 'ST', nombre: 'Santo Tomé y Príncipe' },
    { codigo: 'SA', nombre: 'Arabia Saudita' },
    { codigo: 'SN', nombre: 'Senegal' },
    { codigo: 'RS', nombre: 'Serbia' },
    { codigo: 'SC', nombre: 'Seychelles' },
    { codigo: 'SL', nombre: 'Sierra Leona' },
    { codigo: 'SG', nombre: 'Singapur' },
    { codigo: 'SK', nombre: 'Eslovaquia' },
    { codigo: 'SI', nombre: 'Eslovenia' },
    { codigo: 'SB', nombre: 'Islas Salomón' },
    { codigo: 'SO', nombre: 'Somalia' },
    { codigo: 'ZA', nombre: 'Sudáfrica' },
    { codigo: 'KR', nombre: 'Corea del Sur' },
    { codigo: 'SS', nombre: 'Sudán del Sur' },
    { codigo: 'ES', nombre: 'España' },
    { codigo: 'LK', nombre: 'Sri Lanka' },
    { codigo: 'SD', nombre: 'Sudán' },
    { codigo: 'SR', nombre: 'Surinam' },
    { codigo: 'SE', nombre: 'Suecia' },
    { codigo: 'CH', nombre: 'Suiza' },
    { codigo: 'SY', nombre: 'Siria' },
    { codigo: 'TJ', nombre: 'Tayikistán' },
    { codigo: 'TZ', nombre: 'Tanzania' },
    { codigo: 'TH', nombre: 'Tailandia' },
    { codigo: 'TL', nombre: 'Timor Oriental' },
    { codigo: 'TG', nombre: 'Togo' },
    { codigo: 'TO', nombre: 'Tonga' },
    { codigo: 'TT', nombre: 'Trinidad y Tobago' },
    { codigo: 'TN', nombre: 'Túnez' },
    { codigo: 'TR', nombre: 'Turquía' },
    { codigo: 'TM', nombre: 'Turkmenistán' },
    { codigo: 'TV', nombre: 'Tuvalu' },
    { codigo: 'UG', nombre: 'Uganda' },
    { codigo: 'UA', nombre: 'Ucrania' },
    { codigo: 'AE', nombre: 'Emiratos Árabes Unidos' },
    { codigo: 'GB', nombre: 'Reino Unido' },
    { codigo: 'US', nombre: 'Estados Unidos' },
    { codigo: 'UY', nombre: 'Uruguay' },
    { codigo: 'UZ', nombre: 'Uzbekistán' },
    { codigo: 'VU', nombre: 'Vanuatu' },
    { codigo: 'VA', nombre: 'Ciudad del Vaticano' },
    { codigo: 'VE', nombre: 'Venezuela' },
    { codigo: 'VN', nombre: 'Vietnam' },
    { codigo: 'YE', nombre: 'Yemen' },
    { codigo: 'ZM', nombre: 'Zambia' },
    { codigo: 'ZW', nombre: 'Zimbabue' },
];

export default paises;